#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Update-helloworld

on:
  schedule:
    - cron: 35 19 * * *  

jobs:

  prepare:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Load latest helloworld
      run: |
        git clone https://github.com/fw876/helloworld.git --depth=1 ./tmp/helloworld
        cp -rf ./tmp/helloworld/luci-app-ssr-plus ./package/lean/
        cp -rf ./tmp/helloworld/tcping ./package/lean/
        cp -rf ./tmp/helloworld/naiveproxy ./package/lean/

    - name: Apply commit changes
      run: |
        git add ./package/lean/luci-app-ssr-plus/ ./package/lean/tcping/ ./package/lean/naiveproxy/
        echo -e "[bot] luci-app-ssr-plus: update\n\nlatest commit: $(cat ./tmp/helloworld/.git/refs/heads/master)" > ./tmp/message
        git commit --file="./tmp/message" || exit 0

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
